<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 2

### 1. Form a 1D array containing elements from -2(including) to 10(excluding) in arithmetic progression with common difference 1.5 , negate all elements which are between 2 and 7, in place. Print out this new array.

In [150]:
import numpy as np
def generate():
    arr = np.arange(-2, 10, 1.5)
    arr = arr[(~(arr>2)) | (~(arr<=7))] 
    return arr
generate()

array([-2. , -0.5,  1. ,  8.5])

In [149]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

### 2. Create random vector of size 7 and replace the maximum value by 2 and minimum by 7. Sort this array in reverse order. Return the modified vector.

In [75]:
import numpy as np
def generate():
    randarr = np.random.rand(7)
    sortarr = np.sort(randarr)
    sortarr[0] = 7
    sortarr[len(sortarr)-1] = 2
    print(sortarr)
    return sortarr[::-1]
generate()

[7.         0.2335698  0.32565394 0.40029345 0.44968943 0.57714323
 2.        ]


array([2.        , 0.57714323, 0.44968943, 0.40029345, 0.32565394,
       0.2335698 , 7.        ])

### 3. Convert a random 7x2 matrix representing cartesian coordinates to polar coordinates. Print out both.
Hint: use arctan2().

In [92]:
import numpy as np
def generate():
    arr3 = np.random.rand(7,2)
    print(arr3[:, :])
    print(np.arctan2(arr3[:, 0:1], arr3[:, 1:2]))
    return None
generate()

[[0.00400944 0.75524458]
 [0.25933425 0.02440074]
 [0.3575612  0.79023395]
 [0.69850351 0.22187816]
 [0.91059592 0.94263558]
 [0.75152371 0.77276361]
 [0.57499054 0.71642558]]
[[0.00530875]
 [1.4769826 ]
 [0.42491033]
 [1.26322847]
 [0.76811135]
 [0.77146475]
 [0.67631357]]


### 4. Create an numpy array sequence named num_seq when only the starting point, step size and length of sequence is given.

In [107]:
import numpy as np

length = 15
start = 5
step = 2

def generate(start, length, step):
    num_seq = np.arange(start,(length*step + start-1),step)
    return num_seq
generate(start, length, step)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

### 5. Make a 3*3 array using a 1d array of evenly spaced numbers ranging from 0 to 9, name it arr1.<br/> 
### Then transpose it to obtain arr2.  From arr2 subtract a 1*3 array with all elements 1 to get arr4.
HINT: Use reshape and transpose function.

In [125]:
import numpy as np
def generate():
    arr1 = np.arange(0,9).reshape(3,3)
    arr2 = np.transpose(arr1)
    arr4 = arr2 - [1,1,1]
    return arr4
generate()

array([[-1,  2,  5],
       [ 0,  3,  6],
       [ 1,  4,  7]])

### 6. Create a DatetimeIndex that contains each business day of 2016 and use it to index a Series of random numbers. Let's call this Series bus_2k16. Print it out. Hint: use pd.date_range.

In [250]:
import pandas as pd
import numpy as np

def generate():
    arr5 = np.random.rand(366)
    dti = pd.date_range(start='2016-01-01', end='2016-12-31')
    bus_2k16 = pd.Series(data=arr5, index = dti)
    print(bus_2k16)
    return None
generate()

2016-01-01    0.408914
2016-01-02    0.283648
2016-01-03    0.230615
2016-01-04    0.155157
2016-01-05    0.278682
2016-01-06    0.621733
2016-01-07    0.485637
2016-01-08    0.233729
2016-01-09    0.234060
2016-01-10    0.088226
2016-01-11    0.946409
2016-01-12    0.031390
2016-01-13    0.507358
2016-01-14    0.030351
2016-01-15    0.302945
2016-01-16    0.046102
2016-01-17    0.771829
2016-01-18    0.024479
2016-01-19    0.808769
2016-01-20    0.310985
2016-01-21    0.548182
2016-01-22    0.324258
2016-01-23    0.302198
2016-01-24    0.549634
2016-01-25    0.214553
2016-01-26    0.847281
2016-01-27    0.094461
2016-01-28    0.255221
2016-01-29    0.255629
2016-01-30    0.510837
                ...   
2016-12-02    0.455644
2016-12-03    0.919379
2016-12-04    0.000296
2016-12-05    0.151220
2016-12-06    0.650453
2016-12-07    0.430755
2016-12-08    0.179678
2016-12-09    0.529763
2016-12-10    0.946840
2016-12-11    0.563413
2016-12-12    0.413718
2016-12-13    0.599888
2016-12-14 

###  7. For each calendar month in dataframe bus_2k16, from previous problem. Print out the mean of values also find the sum of the values in bus_2k16 for every Sunday.

In [264]:
import pandas as pd
def generate():
    dti = pd.date_range(start='2016-01-01', end='2016-12-31')
    bus_2k16 = pd.Series(data=np.random.rand(len(dti)), index = dti)
    print("mean of values for each calendar month")
    print(bus_2k16.resample('M', how='mean'))
    print("sum of the values in bus_2k16 for every Sunday ->", bus_2k16[dti.weekday==6].sum())
    return None
generate()

mean of values for each calendar month
2016-01-31    0.487536
2016-02-29    0.520164
2016-03-31    0.495129
2016-04-30    0.620653
2016-05-31    0.566096
2016-06-30    0.423134
2016-07-31    0.508789
2016-08-31    0.524112
2016-09-30    0.499804
2016-10-31    0.451445
2016-11-30    0.529330
2016-12-31    0.509634
Freq: M, dtype: float64
sum of the values in bus_2k16 for every Sunday -> 26.8745239702171


//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...).mean()
  


//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...).mean()
  This is separate from the ipykernel package so we can avoid doing imports until


21.686390868183548

### 8.Given the dataframe df, In the From_To column split each string on the underscore delimiter _ to give a new temporary DataFrame with the correct values. Also standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".) Assign the correct column names to this temporary DataFrame named as temp. Return temp.

In [240]:
import numpy as np
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
import pandas as pd
def generate():
    temp = pd.DataFrame(df['From_To'].str.split('_', expand=True))
    temp[0] = temp[0].str.capitalize()
    temp[1] = temp[1].str.capitalize()
    temp = temp.rename(columns={0: "From", 1: "To"})
    temp
    return temp
generate()

From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

### 9. Given a dataFrame with 10 columns of real numbers. Find that column's label which has the smallest sum? Also count the number of unique rows the dataframe has. 
Hint: use idxmin method.

In [183]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.random(size=(4, 10)), columns=list('qrstuvwxyz'))
print(df)
def generate():
    print(df.sum())
    print(df.sum().idxmin())
    print(df[~df.duplicated(df.columns)].shape[0])
    return None
generate()

          q         r         s         t         u         v         w  \
0  0.148733  0.023968  0.966215  0.676884  0.299551  0.391411  0.017279   
1  0.204436  0.390818  0.209752  0.350600  0.847751  0.622971  0.384937   
2  0.923598  0.285800  0.056364  0.559473  0.999240  0.375411  0.437056   
3  0.271361  0.521707  0.641827  0.439741  0.735128  0.316660  0.857453   

          x         y         z  
0  0.188805  0.547702  0.916410  
1  0.619401  0.859945  0.370053  
2  0.927112  0.459926  0.266455  
3  0.076896  0.875254  0.356783  
q    1.548129
r    1.222293
s    1.874157
t    2.026698
u    2.881671
v    1.706453
w    1.696725
x    1.812214
y    2.742827
z    1.909700
dtype: float64
r
4


't'

### 10. Given a dataFrame df with a column 'int' of integers. Print out the dataframe with filtered out rows which contain the same integer as the row immediately above. Also print out the dataframe after subtracting the mean of all integers from each element .
Hint: use drop_duplicates and sub methods

In [169]:
import pandas as pd
df = pd.DataFrame({'int': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
def generate():
    df1 = df[~df.duplicated()]
    df1.reset_index().drop('index', axis=1)
    print(df1)
    print(df1.mean())
    df2 = df1 - df1.mean()
    print(df2)
    return None
generate()

   int
0    1
1    2
3    3
4    4
5    5
8    6
9    7
int    4.0
dtype: float64
   int
0 -3.0
1 -2.0
3 -1.0
4  0.0
5  1.0
8  2.0
9  3.0
