<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 1

### 1. Create a null vector of size 7 but the third and last value as 2.

In [17]:
import numpy as np
def generate():
    x = np.zeros(10)
    x[2] = 2
    x[-1] = 2
    return x
generate()

array([0., 0., 2., 0., 0., 0., 0., 0., 0., 2.])

### 2. Create a vector of size 9 with values ranging from 0 to 2, both excluded.

In [16]:
import numpy as np
def generate():
    y = np.linspace(0,2,11)[1:-1]
    return y
generate()

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

### 3. Convert the first character of each element in a series to uppercase? And return the new series.

In [23]:
import pandas as pd
series = pd.Series(['how', 'to', 'learn', 'data science?'])
def generate():
    return series.str.title()
generate() 

0              How
1               To
2            Learn
3    Data Science?
dtype: object

### 4. Given a 3*3 matrix named matrix_fab, From each element of this matrix subtract the mean of that row, name this matrix as matrix_sub. Divide each element of this matrix by twice of the largest element to get matrix_norm. Print it out.

In [44]:
import numpy as np
arr = np.arange(0,9)                                
matrix_fab = arr.reshape(3,3)
print(matrix_fab)
def generate():
    ar = matrix_fab.mean(axis=1)
    ar1 = ar.reshape(3,1).astype(int)
#     print(ar1)
    matrix_sub = matrix_fab - ar1
#     print(np.max(matrix_sub))
#     print(matrix_sub)
    print(matrix_sub - 2*np.max(matrix_sub))
    return None
generate()

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-3 -2 -1]
 [-3 -2 -1]
 [-3 -2 -1]]


### 5. Create a random vector of size 12 , sort it in decreasing order, make 4*3 array using it.
Hint: use reshape and sort function.

In [56]:
import numpy as np
def generate():
    ra_var = np.random.rand(12)
    print(ra_var)
    ra_var.sort()
    desc_sort = ra_var[::-1]
    return desc_sort.reshape(4,3)
generate()

[0.38816725 0.5535234  0.62943924 0.9476718  0.53112966 0.88007709
 0.8957788  0.73327508 0.60713143 0.71733379 0.97867889 0.09494306]


array([[0.97867889, 0.9476718 , 0.8957788 ],
       [0.88007709, 0.73327508, 0.71733379],
       [0.62943924, 0.60713143, 0.5535234 ],
       [0.53112966, 0.38816725, 0.09494306]])

### 6. Below is Python dictionary data and Python list labels. Create a DataFrame df from this dictionary data which has index as labels. Select the rows where the age is missing, i.e. is NaN.

In [58]:
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
import pandas as pd
def generate():
    df = pd.DataFrame(data , labels)
    return df[df['age'].isnull()]
generate()

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 7. From the give dataframe df, in the 'animal' column change the 'dog' entries to 'Labrador', change the age in row 'd' to 2.7 and calculate the mean age (name it mean_age) for each different animal in df. Print df and return mean_age.

In [5]:
import pandas as pd
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
def generate():
    df = pd.DataFrame(data, labels)
    df.replace('dog', 'Labrador', inplace=True)
    df.at['d', 'age'] = 2.7
    df['mean_age'] = df['age'].mean()
#     cat_mean = df[df['animal']=='cat']['age'].mean()
#     print(cat_mean)
# df[df['animal']=='cat']['mean_age']
    return df
    
generate()

### 8.  From the given dataframe get the positions where values of two columns match?

In [22]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
def generate():
    print(df)
    return df.index[df['fruit1'] == df['fruit2']].tolist()[0]
generate()

   fruit1  fruit2
0  orange  banana
1  orange   apple
2   apple  orange
3  banana  orange
4   apple  orange
5  orange  banana
6   apple  banana
7  orange   apple
8   apple  orange
9  orange  orange


9

### 9. Find the positions of numbers that are multiples of 4 from a series? Print series and return position. Hint: use argwhere.

In [20]:
import pandas as pd
import numpy as np
series = pd.Series(np.random.randint(1, 10, 7))
def generate():
    print(series)
    print(np.argwhere(series%4==0))
generate()

0    7
1    8
2    3
3    2
4    3
5    7
6    1
dtype: int64
[[1]]


### 10. Stack two given series vertically and horizontally ? Print out both.

In [8]:
import pandas as pd
import numpy as np
series1 = pd.Series(range(5))
series2 = pd.Series(list('abcde'))
def generate():
    print(series1)
    print(series2)
    s3 = pd.concat([series1, series2], axis=0)
    s4 = pd.concat([series1, series2], axis=1)
    print(s3)
    print(s4)
    return None
generate()

0    0
1    1
2    2
3    3
4    4
dtype: int64
0    a
1    b
2    c
3    d
4    e
dtype: object
0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e
