https://towardsdatascience.com/linear-algebra-essentials-with-numpy-part-1-af4a867ac5ca

https://towardsdatascience.com/linear-algebra-essentials-with-numpy-part-2-d15717eebfd9

Vector -  Addition , Scalar Multiplication , Dot Product, Norm, Unit Vector, Angle Between Vectors

In [1]:
import numpy as np

In [2]:
v = np.array([3, 7])
u = np.array([2, 2])
print(v + u)

[5 9]


In [4]:
type(u)

numpy.ndarray

In [5]:
v = np.array([3, 7])
print(2 * v)

[ 6 14]


In [6]:
v = np.array([3, 7])
u = np.array([2, 2])
print(v.dot(u))

20


In [7]:
v = np.array([3, 2, 7])
print(np.linalg.norm(v))

7.874007874011811


In [8]:
def unit_vector(v):
    return v / np.linalg.norm(v)
u = np.array([3, 6, 4])
print(unit_vector(u))

[0.38411064 0.76822128 0.51214752]


In [9]:
def angle_between(v1, v2):
    dot_pr = v1.dot(v2)
    norms = np.linalg.norm(v1) * np.linalg.norm(v2)
 
    return np.rad2deg(np.arccos(dot_pr / norms))
v = np.array([1, 4, 5])
u = np.array([2, 1, 5])
print(angle_between(v, u))

29.152519407030084


In [10]:
A = np.matrix([
    [3, 5],
    [1, 0]
])
B = np.matrix([
    [2, -3],
    [1, 2]
])
print(A + B)

[[5 2]
 [2 2]]


In [11]:
type(A)

numpy.matrix

In [12]:
A = np.matrix([
    [3, 5],
    [1, 0]
])
print(2 * A)

[[ 6 10]
 [ 2  0]]


In [13]:
A = np.matrix([
    [3, 4],
    [1, 0]
])
B = np.matrix([
    [2, 2],
    [1, 2]
])
print(A.dot(B))

[[10 14]
 [ 2  2]]


In [14]:
A = np.matrix([
    [3, 4],
    [1, 0]
])
print(A.T)

[[3 1]
 [4 0]]


In [15]:
A = np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
A = np.matrix([
    [3, 2],
    [1, 6]
])
print(np.linalg.det(A))

16.000000000000007
